### ISSUE TITLE
Can't build with gradle

### ISSUE THREAD

**Issue by BitBoxGaming** [afollestad/icon-request#1]
After adding 

`dependencies {
    compile 'com.afollestad:icon-request:1.3.8'
}`

The project is unable to build as it "Could not find com.afollestad:icon-request:1.3.8."

Full error log:

`Error:A problem occurred configuring project ':app'.

> Could not resolve all dependencies for configuration ':app:_debugCompile'.
> Could not find com.afollestad:icon-request:1.3.8.
>      Searched in the following locations:
>          file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/afollestad/icon-request/1.3.8/icon-request-1.3.8.pom
>          file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/afollestad/icon-request/1.3.8/icon-request-1.3.8.pom
>          https://jcenter.bintray.com/com/afollestad/icon-request/1.3.8/icon-request-1.3.8.pom
>          https://jcenter.bintray.com/com/afollestad/icon-request/1.3.8/icon-request-1.3.8.pom
>          file:/C:/Users/User 1/AppData/Local/Android/Sdk/extras/android/m2repository/com/afollestad/icon-request/1.3.8/icon-request-1.3.8.pom
>          file:/C:/Users/User 1/AppData/Local/Android/Sdk/extras/android/m2repository/com/afollestad/icon-request/1.3.8/icon-request-1.3.8.pom
>          file:/C:/Users/User 1/AppData/Local/Android/Sdk/extras/google/m2repository/com/afollestad/icon-request/1.3.8/icon-request-1.3.8.pom
>          file:/C:/Users/User 1/AppData/Local/Android/Sdk/extras/google/m2repository/com/afollestad/icon-request/1.3.8/icon-request-1.3.8.pom
>      Required by:
>          Android-Navigation-Drawer-master:app:unspecified`

**Comment by PDDStudio** [comment]
The project is unable to build as it "Could not find com.afollestad:icon-request:1.3.8_._"
Is the last "_. (DOT)_" supposed to be there?
Also make sure you added the maven repository `https://dl.bintray.com/drummer-aidan/maven/`to your build file.

**Comment by BitBoxGaming** [comment]
Wow, I'm an idiot. Thanks!
