### ISSUE TITLE
Can not get AppModel List  java.lang.Exception: Failed to read appfilter.xml arctic-icon-request

### ISSUE THREAD

**Issue by MehulKK** [afollestad/icon-request#3]
I am integrate arctic icon request lib, here is my code

PolarConfig config = PolarConfig.create(getActivity())
                //.apiHost("https://your-server.com") // optional, specify for Request Manager usage
                .apiKey("API_KEY") // optional, specify for Request Manager usage
                .emailRecipient(getResources().getString(R.string.dev_email)) // required IF you don't specify an API key
                .appFilterName("appfilter.xml")
                .cacheFolder(getActivity().getCacheDir().getAbsolutePath())
                .errorOnInvalidDrawables(true)
                .includeDeviceInfo(true)
                .emailSubject("New Icon Request")
                .emailHeader("These apps are unthemed!")
                .emailFooter("Thank you!")
                .build();

        request =
                PolarRequest.make(getActivity(), savedInstanceState)
                        .config(config)
                        .uriTransformer(
                                uri ->
                                        FileProvider.getUriForFile(
                                                getActivity(),
                                                BuildConfig.APPLICATION_ID + ".fileProvider",
                                                new File(uri.getPath())));

        request.loaded()
                .subscribe(loadResult -> {
                    if (loadResult.success()) {
                        List<AppModel> apps = loadResult.apps();
                        // Use apps
                    } else {
                        Exception error = loadResult.error();
                        // Use error
                    }
                });

in Expectation i got below one 
java.lang.Exception: Failed to read appfilter.xml arctic-icon-request

Thanks in Advance

**Comment by afollestad** [comment]
Please try the latest release.

You may want to `printStackTrace()` on the Exception object.

**Comment by afollestad** [comment]
https://github.com/afollestad/arctic-icon-request/releases/tag/4.1.0
