### ISSUE TITLE
Failed to resolve 'com.afollestad:icon-request:4.0.3'

### ISSUE THREAD

**Issue by Silverblade30** [afollestad/icon-request#4]
- [ Y] I have verified there are no duplicate active or recent bugs, questions, or requests
- [Y ] I have verified that I am using the latest version of this library.
- [ Y] I have given my issue a non-generic title.

###### Include the following:
 - Library version: `4.0.3`
 - Device OS version: `8.1.0`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`

Also, please wrap Java with correct syntax highlighting.

###### Reproduction Steps

1.  add "compile 'com.afollestad:icon-request:4.0.3' " in dependencies
2. 
3. 

###### Expected Result

library gets synced

###### Actual Result

Error stating "Failed to resolve 'com.afollestad:icon-request:4.0.3'"

**Comment by afollestad** [comment]
Well, it's definitely available: https://bintray.com/drummer-aidan/maven/icon-request/4.0.3

You may be missing a repository definition?

**Comment by afollestad** [comment]
https://github.com/afollestad/arctic-icon-request/releases/tag/4.1.0
