### ISSUE TITLE
Sample giving error 429 on sending requests

### ISSUE THREAD

**Issue by Silverblade30** [afollestad/icon-request#5]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of this library.
- [x] I have given my issue a non-generic title.

###### Include the following:
 - Library version: `4.0.3`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`

 
###### Reproduction Steps

1.  Created package on arcticmanager.com
2.  changed sample project same as arcticmanager.com
3.  added API key received from arcticmanager.com

###### Expected Result

icon request gets synced with arcticmanger.com

###### Actual Result
Error 429

**Comment by afollestad** [comment]
429 means you've sent too many continuous requests and are being rate limited.

**Comment by Silverblade30** [comment]
I have clicked on send request only once and also have waited 600sec cooldown period to try again but still getting same error. Also facing issue if i replace the included appfilter with appfilter of my icon pack which i believe is caused by iconback and iconupon entries in appfilter.

**Comment by afollestad** [comment]
Hmm, weird.

I have Arctic Manager configured to allow 5 requests within a 10 minute interval so there should be no issues. I haven't noticed any issues with live icon packs using it either. 🤔 

<img width="219" alt="screen shot 2018-07-09 at 9 00 04 pm" src="https://user-images.githubusercontent.com/1820165/42488595-25125f90-83bb-11e8-9e8e-6860aa8af179.png">

**Comment by afollestad** [comment]
Have you tried using Blueprint dashboard directly? I'm wondering if there's an issue going on specifically in this lib now

**Comment by jahirfiquitiva** [comment]
@afollestad Blueprint is working fine but I am not using your library 😅

**Comment by afollestad** [comment]
Yeah that's why I think there may be an issue in this lib that I haven't seen 😁

**Comment by worstkiller** [comment]
I have seen the bin tray site also for gradle dependencies and I couldn't see anything there as it not able to resolve the dependency from [jcenter](http://repo.jfrog.org/artifactory/libs-release-bintray/com/affollestad/icon-request/) , as a fallback right now I am using the sample provided in project and library as local module with things configured all properly and getting the error 429 and 400 randomly.

It would be better if you give us some working example using the gradle dependency.
Thanks

**Comment by Silverblade30** [comment]
With Blueprint, it works flawlessly but sample is having trouble sending requests.
Here are some Logcats :
1. https://pastebin.com/fXc5LKv4
2. https://pastebin.com/CuV5erXm (tried after appx 15 minutes from first test)

**Comment by afollestad** [comment]
Fixed https://github.com/afollestad/arctic-icon-request/releases/tag/4.1.0

**Comment by Silverblade30** [comment]
Great! Thank you. Will check it out.
